# trabajamos con javascript
language: node_js
cache: 
  directories:
    - node_modules # mantener en cache node_modules
    - ~/.npm

node_js:
  - '12.18.3'
git:
  depth: 3

script:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: gh-pages
  commit_message: "Project Deploy"
  on:
    branch: master

